---
title: "Sleep Revolution"
author: "Jani Miettinen, Ida Alakörkkö, Anna But, Reijo Sund"
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    lib_dir: "book_assets"
    config:
      toc:
        collapse: section
        scroll_highlight: yes
        before: null
        after: null
      toolbar:
        position: fixed
      edit : null
      download: null
      search: yes
      fontsettings:
        theme: white
        family: sans
        size: 2
      sharing: no
  bookdown::pdf_book:
    keep_tex: yes
---
