---
title: "PAF"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Unit check that PAF calculations are ok

```{r}
# Type 2 diabetes moderate-severe
## PAF 14,5% = 0.145
P =  # 0.27 #  6.8 
RR = 1.63
PAF = (P*(RR -1)) / (P*(RR-1)+1)
PAF
## Miksi ei tasmaa??

## käytetään uniapnean prevalenssia
```




## Use Italy data from article and calculate PAF

```{r}
# paf_or(OR, prevalence, osa_table()$rate[osa_table()$gender == "Both" & osa_table()$var == "Moderate-Severe"])
## käytetään myös taudin prevalenssia
## TODO laske armenin artikkelin luvuilla testi


paf_or <- function(OR, PD, PE){
  PE_ = 100 - PE
  VALUE1 = (PD * (1 - OR) + PE_ + OR * PE + sqrt( (PD * (1 - OR) + PE_ + OR * PE )^2 - 4 * PE_ * (1 - OR) *PD )) / (2 * PE_ * (1 - OR))
  VALUE2 = (PD * (1 - OR) + PE_ + OR * PE - sqrt( (PD * (1 - OR) + PE_ + OR * PE )^2 - 4 * PE_ * (1 - OR) *PD )) / (2 * PE_ * (1 - OR))
  VALUE <- ifelse(VALUE1 < 100 & VALUE1 > 0, VALUE1, VALUE2)
  PAF = 1 - ((100 * VALUE) / PD)
  return(PAF)
}
# PD  ## having a disease, prevalence
# PE  ## exposed, sleep apnea prevalence?
# PE_ ##  unexposed, 
# Glaucoma OR 1.24 / PD 0.018
# Diabetic retipathy OR 2.01 / PD 0.026
#  conservative approach
paf_or( 1.24, 1.8, 27) # 0.05966  / 6 %
paf_or( 2.01, 2.6, 27) # 0.207377 / 20.7&
## eli luvut pitaa olla prosentteja

## testataan onnistuuko desimaaleilla
paf_or <- function(OR, PD, PE){
  PD = PD * 100
  PE = PE * 100
  PE_ = 100 - PE
  VALUE1 = (PD * (1 - OR) + PE_ + OR * PE + sqrt( (PD * (1 - OR) + PE_ + OR * PE )^2 - 4 * PE_ * (1 - OR) *PD )) / (2 * PE_ * (1 - OR))
  VALUE2 = (PD * (1 - OR) + PE_ + OR * PE - sqrt( (PD * (1 - OR) + PE_ + OR * PE )^2 - 4 * PE_ * (1 - OR) *PD )) / (2 * PE_ * (1 - OR))
  VALUE <- ifelse(VALUE1 < 100 & VALUE1 > 0, VALUE1, VALUE2)
  PAF = 1 - ((100 * VALUE) / PD)
  return(PAF)
}

paf_or( 1.24, 0.018, 0.27) # 0.05966  / 6 %
paf_or( 2.01, 0.026, 0.27) # 0.207377 / 20.7&
```

```{r}
library(tidyverse)
d <- readxl::read_xlsx("/Users/japmiett/projects/sleep22/data/osa_tables.xlsx", sheet = "tbl2")

d %>% 
  mutate(
    ## PAF formula from TODO ADD SOURCE. Is it specific for Armeni?
    PAFRR = ifelse(!is.na(RR), (prevalence_base_italy * (RR - 1) / (prevalence_base_italy * (RR - 1) + 1)), NA), 
    PAFRR2 = ifelse(!is.na(RR), (100*prevalence_base_italy * (RR - 1) / (100*prevalence_base_italy * (RR - 1) + 1)), NA), 
    # TODO here PAF calculation for OR
    PAFOR = ifelse(!is.na(OR), paf_or(OR, prevalence_base_italy, 0.27), NA)
  ) %>% 
    select(cause_id, Conditon, prevalence_base_italy, OR, RR, PAF, PAFRR, PAFRR2, PAFOR) -> d_tmp
```


